// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef STELLARSDK_SWIFT_H
#define STELLARSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="stellarsdk",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// Represents the account balance.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/account.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk22AccountBalanceResponse")
@interface AccountBalanceResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents an account effect response. Superclass for all other effect response classes.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk14EffectResponse")
@interface EffectResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents an account created effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk28AccountCreatedEffectResponse")
@interface AccountCreatedEffectResponse : EffectResponse
@end


/// Represents an operation response. Superclass for all other operation response classes.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/operation.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk17OperationResponse")
@interface OperationResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents an account created operation response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/operation.html#create-account">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk31AccountCreatedOperationResponse")
@interface AccountCreatedOperationResponse : OperationResponse
@end


/// Represents an account credited effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk29AccountCreditedEffectResponse")
@interface AccountCreditedEffectResponse : EffectResponse
@end


/// Represents an account debited effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk28AccountDebitedEffectResponse")
@interface AccountDebitedEffectResponse : EffectResponse
@end


/// Represents the account flags.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/account.html">Horizon API</a>
/// See [Stellar Guides] (https://www.stellar.org/developers/guides/concepts/accounts.html#flags “Account flags”)
/// Currently there are three flags, used by issuers of assets: Authorization required, Authorization revocable and Authorization immutable.
SWIFT_CLASS("_TtC10stellarsdk20AccountFlagsResponse")
@interface AccountFlagsResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents an account flags updated effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/accounts.html#flags">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk33AccountFlagsUpdatedEffectResponse")
@interface AccountFlagsUpdatedEffectResponse : EffectResponse
@end


/// Represents an account home domain updated effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/accounts.html#home-domain">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk38AccountHomeDomainUpdatedEffectResponse")
@interface AccountHomeDomainUpdatedEffectResponse : EffectResponse
@end


/// Represents an inflation destination updated effect response. See superclass InflationDestinationUpdatedEffect.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/assets.html#inflation">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk48AccountInflationDestinationUpdatedEffectResponse")
@interface AccountInflationDestinationUpdatedEffectResponse : EffectResponse
@end


/// Represents the links contained within an account response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/account.html#links">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk20AccountLinksResponse")
@interface AccountLinksResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents an account merge operation response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/operation.html#account-merge">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk29AccountMergeOperationResponse")
@interface AccountMergeOperationResponse : OperationResponse
@end


/// Represents an account removed effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk28AccountRemovedEffectResponse")
@interface AccountRemovedEffectResponse : EffectResponse
@end


/// Represents an account response, containing information and links relating to a single account.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/account.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk15AccountResponse")
@interface AccountResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Class that handles account related calls.
SWIFT_CLASS("_TtC10stellarsdk14AccountService")
@interface AccountService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents the account signer response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/account.html">Horizon API</a>
/// See [Stellar Guides] (https://www.stellar.org/developers/guides/concepts/accounts.html#signers “Account signers”)
/// Currently there are three flags, used by issuers of assets: Authorization required, Authorization revocable and Authorization immutable.
SWIFT_CLASS("_TtC10stellarsdk21AccountSignerResponse")
@interface AccountSignerResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk39AccountSponsorshipCreatedEffectResponse")
@interface AccountSponsorshipCreatedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk39AccountSponsorshipRemovedEffectResponse")
@interface AccountSponsorshipRemovedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk39AccountSponsorshipUpdatedEffectResponse")
@interface AccountSponsorshipUpdatedEffectResponse : EffectResponse
@end


/// Represents account thresholds.
/// See <a href="https://www.stellar.org/developers/guides/concepts/multi-sig.html#thresholds">Stellar documentation</a>
SWIFT_CLASS("_TtC10stellarsdk25AccountThresholdsResponse")
@interface AccountThresholdsResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents an account thresholds updated effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/multi-sig.html#thresholds">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk38AccountThresholdsUpdatedEffectResponse")
@interface AccountThresholdsUpdatedEffectResponse : EffectResponse
@end


/// Represents an allow trust operation response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/operation.html#allow-trust">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk27AllowTrustOperationResponse")
@interface AllowTrustOperationResponse : OperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk13AssetAccounts")
@interface AssetAccounts : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk18AssetBalanceChange")
@interface AssetBalanceChange : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk13AssetBalances")
@interface AssetBalances : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents the links connected to an asset response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/asset.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk18AssetLinksResponse")
@interface AssetLinksResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents an asset response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/endpoints/assets-all.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/asset.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk13AssetResponse")
@interface AssetResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk13AssetsService")
@interface AssetsService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents an error response from the horizon api, containing information related to the error that occured.
/// See <a href="https://www.stellar.org/developers/horizon/reference/errors.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk13ErrorResponse")
@interface ErrorResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a bad request error response from the horizon api (code 400), containing information related to the error
/// See <a href="https://www.stellar.org/developers/horizon/reference/errors/bad-request.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk23BadRequestErrorResponse")
@interface BadRequestErrorResponse : ErrorResponse
@end


/// Represents a before history error response from the horizon api (code 410), containing information related to the error
/// See <a href="https://www.stellar.org/developers/horizon/reference/errors/before-history.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk26BeforeHistoryErrorResponse")
@interface BeforeHistoryErrorResponse : ErrorResponse
@end


SWIFT_CLASS("_TtC10stellarsdk46BeginSponsoringFutureReservesOperationResponse")
@interface BeginSponsoringFutureReservesOperationResponse : OperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk29BumpSequenceOperationResponse")
@interface BumpSequenceOperationResponse : OperationResponse
@end


/// Represents a change trust operation response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/operation.html#change-trust">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk28ChangeTrustOperationResponse")
@interface ChangeTrustOperationResponse : OperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk38ClaimClaimableBalanceOperationResponse")
@interface ClaimClaimableBalanceOperationResponse : OperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk45ClaimableBalanceClaimantCreatedEffectResponse")
@interface ClaimableBalanceClaimantCreatedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk37ClaimableBalanceClaimedEffectResponse")
@interface ClaimableBalanceClaimedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk40ClaimableBalanceClawedBackEffectResponse")
@interface ClaimableBalanceClawedBackEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk37ClaimableBalanceCreatedEffectResponse")
@interface ClaimableBalanceCreatedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk29ClaimableBalanceLinksResponse")
@interface ClaimableBalanceLinksResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk24ClaimableBalanceResponse")
@interface ClaimableBalanceResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk48ClaimableBalanceSponsorshipCreatedEffectResponse")
@interface ClaimableBalanceSponsorshipCreatedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk48ClaimableBalanceSponsorshipRemovedEffectResponse")
@interface ClaimableBalanceSponsorshipRemovedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk48ClaimableBalanceSponsorshipUpdatedEffectResponse")
@interface ClaimableBalanceSponsorshipUpdatedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk24ClaimableBalancesService")
@interface ClaimableBalancesService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk25ClaimantPredicateResponse")
@interface ClaimantPredicateResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk16ClaimantResponse")
@interface ClaimantResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk41ClawbackClaimableBalanceOperationResponse")
@interface ClawbackClaimableBalanceOperationResponse : OperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk25ClawbackOperationResponse")
@interface ClawbackOperationResponse : OperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk30ContractCreditedEffectResponse")
@interface ContractCreditedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk29ContractDebitedEffectResponse")
@interface ContractDebitedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk39CreateClaimableBalanceOperationResponse")
@interface CreateClaimableBalanceOperationResponse : OperationResponse
@end


/// Represents a create passive operation response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/operation.html#create-passive-offer">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk35CreatePassiveOfferOperationResponse")
@interface CreatePassiveOfferOperationResponse : OperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk39CreatePassiveSellOfferOperationResponse")
@interface CreatePassiveSellOfferOperationResponse : CreatePassiveOfferOperationResponse
@end


/// Represents a data created effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk25DataCreatedEffectResponse")
@interface DataCreatedEffectResponse : EffectResponse
@end


/// Represents a data for account response from the Horizon API, conating a single data value associated with a given account and requested key.
/// See <a href="https://www.stellar.org/developers/horizon/reference/endpoints/data-for-account.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk22DataForAccountResponse")
@interface DataForAccountResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a data created effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk25DataRemovedEffectResponse")
@interface DataRemovedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk36DataSponsorshipCreatedEffectResponse")
@interface DataSponsorshipCreatedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk36DataSponsorshipRemovedEffectResponse")
@interface DataSponsorshipRemovedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk36DataSponsorshipUpdatedEffectResponse")
@interface DataSponsorshipUpdatedEffectResponse : EffectResponse
@end


/// Represents a data created effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk25DataUpdatedEffectResponse")
@interface DataUpdatedEffectResponse : EffectResponse
@end



SWIFT_CLASS("_TtC10stellarsdk22DuplicateErrorResponse")
@interface DuplicateErrorResponse : ErrorResponse
@end


/// Represents the links connected to an effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk19EffectLinksResponse")
@interface EffectLinksResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// Builds requests connected to effects.
SWIFT_CLASS("_TtC10stellarsdk14EffectsService")
@interface EffectsService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk17EffectsStreamItem")
@interface EffectsStreamItem : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk44EndSponsoringFutureReservesOperationResponse")
@interface EndSponsoringFutureReservesOperationResponse : OperationResponse
@end



/// Part of the getEvents respopnse
/// See https://developers.stellar.org/network/soroban-rpc/api-reference/methods/getEvents
SWIFT_CLASS("_TtC10stellarsdk9EventInfo")
@interface EventInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURLSession;
@class NSURLSessionDataTask;
@class NSData;
@class NSURLResponse;
@class NSURLSessionTask;

SWIFT_CLASS("_TtC10stellarsdk11EventSource")
@interface EventSource : NSObject <NSURLSessionDataDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveData:(NSData * _Nonnull)data;
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveResponse:(NSURLResponse * _Nonnull)response completionHandler:(void (^ _Nonnull)(NSURLSessionResponseDisposition))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk35ExtendFootprintTTLOperationResponse")
@interface ExtendFootprintTTLOperationResponse : OperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk10Federation")
@interface Federation : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk29FeeBumpTransactionEnvelopeXDR")
@interface FeeBumpTransactionEnvelopeXDR : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk26FeeBumpTransactionResponse")
@interface FeeBumpTransactionResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk18FeeChargedResponse")
@interface FeeChargedResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk16FeeStatsResponse")
@interface FeeStatsResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Class that handles fee stats related calls.
SWIFT_CLASS("_TtC10stellarsdk15FeeStatsService")
@interface FeeStatsService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a forbidden error response from the horizon api (code 403), containing information related to the error
/// See <a href="https://www.stellar.org/developers/horizon/reference/errors/forbidden.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk22ForbiddenErrorResponse")
@interface ForbiddenErrorResponse : ErrorResponse
@end


SWIFT_CLASS("_TtC10stellarsdk17GetEventsResponse")
@interface GetEventsResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk19GetFeeStatsResponse")
@interface GetFeeStatsResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// General node health check response.
SWIFT_CLASS("_TtC10stellarsdk17GetHealthResponse")
@interface GetHealthResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Response for the getLatestLedger request
/// See: https://developers.stellar.org/network/soroban-rpc/api-reference/methods/getLatestLedger
SWIFT_CLASS("_TtC10stellarsdk23GetLatestLedgerResponse")
@interface GetLatestLedgerResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Response for the getLedgerEntry request
/// See: https://developers.stellar.org/network/soroban-rpc/api-reference/methods/getLedgerEntries
SWIFT_CLASS("_TtC10stellarsdk24GetLedgerEntriesResponse")
@interface GetLedgerEntriesResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// General info about the currently configured network.
/// See: https://developers.stellar.org/network/soroban-rpc/api-reference/methods/getNetwork
SWIFT_CLASS("_TtC10stellarsdk18GetNetworkResponse")
@interface GetNetworkResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Response when polling the rpc server to find out if a transaction has been
/// completed.
/// See: https://developers.stellar.org/network/soroban-rpc/api-reference/methods/getTransaction
SWIFT_CLASS("_TtC10stellarsdk22GetTransactionResponse")
@interface GetTransactionResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk23GetTransactionsResponse")
@interface GetTransactionsResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk22GetVersionInfoResponse")
@interface GetVersionInfoResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk12InclusionFee")
@interface InclusionFee : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents an inflation operation response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/operation.html#inflation">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk26InflationOperationResponse")
@interface InflationOperationResponse : OperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk24InnerTransactionResponse")
@interface InnerTransactionResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Implements SEP-0024 - Hosted Deposit and Withdrawal.
/// See <https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md” target=”_blank”>Hosted Deposit and Withdrawal</a>
SWIFT_CLASS("_TtC10stellarsdk18InteractiveService")
@interface InteractiveService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents an internal server error response from the horizon api, containing information related to the error
/// See <a href="https://www.stellar.org/developers/horizon/reference/errors/server-error.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk27InternalServerErrorResponse")
@interface InternalServerErrorResponse : ErrorResponse
@end


SWIFT_CLASS("_TtC10stellarsdk35InvokeHostFunctionOperationResponse")
@interface InvokeHostFunctionOperationResponse : OperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk10KycService")
@interface KycService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk11LedgerEntry")
@interface LedgerEntry : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk17LedgerEntryChange")
@interface LedgerEntryChange : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents the links connected to a ledger response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/ledger.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk19LedgerLinksResponse")
@interface LedgerLinksResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a ledger response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/ledger.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk14LedgerResponse")
@interface LedgerResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk14LedgersService")
@interface LedgersService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk17LedgersStreamItem")
@interface LedgersStreamItem : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a link response. Used for different responses such as for an account response or ledger response from the Horizon API.
SWIFT_CLASS("_TtC10stellarsdk12LinkResponse")
@interface LinkResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk34LiquidityPoolCreatedEffectResponse")
@interface LiquidityPoolCreatedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk36LiquidityPoolDepositedEffectResponse")
@interface LiquidityPoolDepositedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk36LiquidityPoolDepostOperationResponse")
@interface LiquidityPoolDepostOperationResponse : OperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk27LiquidityPoolEffectResponse")
@interface LiquidityPoolEffectResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk26LiquidityPoolLinksResponse")
@interface LiquidityPoolLinksResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk26LiquidityPoolPriceResponse")
@interface LiquidityPoolPriceResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk34LiquidityPoolRemovedEffectResponse")
@interface LiquidityPoolRemovedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk21LiquidityPoolResponse")
@interface LiquidityPoolResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk34LiquidityPoolRevokedEffectResponse")
@interface LiquidityPoolRevokedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk32LiquidityPoolTradeEffectResponse")
@interface LiquidityPoolTradeEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk32LiquidityPoolTradesLinksResponse")
@interface LiquidityPoolTradesLinksResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk27LiquidityPoolTradesResponse")
@interface LiquidityPoolTradesResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk38LiquidityPoolWithdrawOperationResponse")
@interface LiquidityPoolWithdrawOperationResponse : OperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk35LiquidityPoolWithdrewEffectResponse")
@interface LiquidityPoolWithdrewEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk21LiquidityPoolsService")
@interface LiquidityPoolsService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a manage offer operation response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/operation.html#manage-offer">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk28ManageOfferOperationResponse")
@interface ManageOfferOperationResponse : OperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk31ManageBuyOfferOperationResponse")
@interface ManageBuyOfferOperationResponse : ManageOfferOperationResponse
@end


/// Represents a manage data operation response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/operation.html#manage-data">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk27ManageDataOperationResponse")
@interface ManageDataOperationResponse : OperationResponse
@end



SWIFT_CLASS("_TtC10stellarsdk32ManageSellOfferOperationResponse")
@interface ManageSellOfferOperationResponse : ManageOfferOperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk14MaxFeeResponse")
@interface MaxFeeResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a not acceptable error response from the horizon api (code 406), containing information related to the error
/// See <a href="https://www.stellar.org/developers/horizon/reference/errors/not-acceptable.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk26NotAcceptableErrorResponse")
@interface NotAcceptableErrorResponse : ErrorResponse
@end


/// Represents a not found error response from the horizon api (code 404), containing information related to the error
/// See <a href="https://www.stellar.org/developers/horizon/reference/errors/not-found.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk21NotFoundErrorResponse")
@interface NotFoundErrorResponse : ErrorResponse
@end


/// Represents a not implemented error response from the horizon api (code 501), containing information related to the error
/// See <a href="https://www.stellar.org/developers/horizon/reference/errors/not-implemented.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk27NotImplementedErrorResponse")
@interface NotImplementedErrorResponse : ErrorResponse
@end


/// Represents the offer asset(selling/buying) attribute.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/offer.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk18OfferAssetResponse")
@interface OfferAssetResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents an offer created effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/exchange.html#offers">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk26OfferCreatedEffectResponse")
@interface OfferCreatedEffectResponse : EffectResponse
@end


/// Represents the links connected to an offer response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/offer.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk18OfferLinksResponse")
@interface OfferLinksResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents an offer price_r attribute.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/offer.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk18OfferPriceResponse")
@interface OfferPriceResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents an offer removed effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/exchange.html#offers">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk26OfferRemovedEffectResponse")
@interface OfferRemovedEffectResponse : EffectResponse
@end


/// Represents a offer response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/offer.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk13OfferResponse")
@interface OfferResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents an offer updated effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/exchange.html#offers">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk26OfferUpdatedEffectResponse")
@interface OfferUpdatedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk13OffersService")
@interface OffersService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk16OffersStreamItem")
@interface OffersStreamItem : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents the links connected to an operation response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/operation.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk22OperationLinksResponse")
@interface OperationLinksResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC10stellarsdk17OperationsService")
@interface OperationsService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk20OperationsStreamItem")
@interface OperationsStreamItem : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a orderbook offer(bids/asks).
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/orderbook.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk22OrderbookOfferResponse")
@interface OrderbookOfferResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a orderbook response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/orderbook.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk17OrderbookResponse")
@interface OrderbookResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk16OrderbookService")
@interface OrderbookService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk19OrderbookStreamItem")
@interface OrderbookStreamItem : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk19PagingLinksResponse")
@interface PagingLinksResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk17ParameterResponse")
@interface ParameterResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a path payment operation response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/operation.html#path-payment">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk28PathPaymentOperationResponse")
@interface PathPaymentOperationResponse : OperationResponse
@end


/// Represents a path payment strict receive operation response.
SWIFT_CLASS("_TtC10stellarsdk41PathPaymentStrictReceiveOperationResponse")
@interface PathPaymentStrictReceiveOperationResponse : PathPaymentOperationResponse
@end


/// Represents a path payment strict send operation response.
SWIFT_CLASS("_TtC10stellarsdk38PathPaymentStrictSendOperationResponse")
@interface PathPaymentStrictSendOperationResponse : PathPaymentOperationResponse
@end


/// Represents a payment operation response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/operation.html#payment">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk24PaymentOperationResponse")
@interface PaymentOperationResponse : OperationResponse
@end


/// Represents a Payment Path response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/path.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk19PaymentPathResponse")
@interface PaymentPathResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk19PaymentPathsService")
@interface PaymentPathsService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Builds requests connected to payments.
SWIFT_CLASS("_TtC10stellarsdk15PaymentsService")
@interface PaymentsService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk33PreconditionsLedgerBoundsResponse")
@interface PreconditionsLedgerBoundsResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk31PreconditionsTimeBoundsResponse")
@interface PreconditionsTimeBoundsResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Implements SEP-0038 - Anchor RFQ API
/// See <https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0038.md” target=”_blank”>Anchor RFQ API.</a>
SWIFT_CLASS("_TtC10stellarsdk12QuoteService")
@interface QuoteService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a rate limit exceeded error response from the horizon api, containing information related to the error
/// See <a href="https://www.stellar.org/developers/horizon/reference/errors/rate-limit-exceeded.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk30RateLimitExceededErrorResponse")
@interface RateLimitExceededErrorResponse : ErrorResponse
@end


/// Implements SEP-0030 - Account Recovery: multi-party recovery of Stellar accounts.
/// See <https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0030.md” target=”_blank”>Account Recovery: multi-party recovery of Stellar accounts.</a>
SWIFT_CLASS("_TtC10stellarsdk15RecoveryService")
@interface RecoveryService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Implements SEP-0008 - Regulated Assets
/// See <https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0008.md” target=”_blank”>Regulated Assets</a>
SWIFT_CLASS("_TtC10stellarsdk22RegulatedAssetsService")
@interface RegulatedAssetsService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk15ReserveResponse")
@interface ReserveResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk33RestoreFootprintOperationResponse")
@interface RestoreFootprintOperationResponse : OperationResponse
@end


/// It can only present on successful simulation (i.e. no error) of InvokeHostFunction operations. If present, it indicates
/// the simulation detected expired ledger entries which requires restoring with the submission of a RestoreFootprint
/// operation before submitting the InvokeHostFunction operation. The restorePreamble.minResourceFee and restorePreamble.transactionData fields should
/// be used to construct the transaction containing the RestoreFootprint
SWIFT_CLASS("_TtC10stellarsdk15RestorePreamble")
@interface RestorePreamble : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk34RevokeSponsorshipOperationResponse")
@interface RevokeSponsorshipOperationResponse : OperationResponse
@end


/// Response when submitting a real transaction to the stellar network.
/// See:  https://developers.stellar.org/network/soroban-rpc/api-reference/methods/sendTransaction
SWIFT_CLASS("_TtC10stellarsdk23SendTransactionResponse")
@interface SendTransactionResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk28SequenceBumpedEffectResponse")
@interface SequenceBumpedEffectResponse : EffectResponse
@end


/// Represents a set options operation response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/operation.html#set-options">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk27SetOptionsOperationResponse")
@interface SetOptionsOperationResponse : OperationResponse
@end


SWIFT_CLASS("_TtC10stellarsdk34SetTrustLineFlagsOperationResponse")
@interface SetTrustLineFlagsOperationResponse : OperationResponse
@end


/// Represents an account signer (create,update,remove) effect response. Superclass for signer created, signer updated and signer removed effects.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/accounts.html#signers">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk20SignerEffectResponse")
@interface SignerEffectResponse : EffectResponse
@end


/// Represents an account signer created effect response. See superclass SignerEffect.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/accounts.html#signers">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk27SignerCreatedEffectResponse")
@interface SignerCreatedEffectResponse : SignerEffectResponse
@end



/// Represents an account signer creted effect response. See superclass SignerEffect.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/accounts.html#signers">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk27SignerRemovedEffectResponse")
@interface SignerRemovedEffectResponse : SignerEffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk38SignerSponsorshipCreatedEffectResponse")
@interface SignerSponsorshipCreatedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk38SignerSponsorshipRemovedEffectResponse")
@interface SignerSponsorshipRemovedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk38SignerSponsorshipUpdatedEffectResponse")
@interface SignerSponsorshipUpdatedEffectResponse : EffectResponse
@end


/// Represents an account signer creted effect response. See superclass SignerEffect.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/accounts.html#signers">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk27SignerUpdatedEffectResponse")
@interface SignerUpdatedEffectResponse : SignerEffectResponse
@end


/// The cost object is legacy, inaccurate, and will be deprecated in future RPC releases. Please decode transactionData XDR to retrieve the correct resources.
SWIFT_CLASS("_TtC10stellarsdk23SimulateTransactionCost")
@interface SimulateTransactionCost : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Response that will be received when submitting a trial contract invocation.
SWIFT_CLASS("_TtC10stellarsdk27SimulateTransactionResponse")
@interface SimulateTransactionResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk25SimulateTransactionResult")
@interface SimulateTransactionResult : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents astale history error response (code 503) from the horizon api, containing information related to the error
/// See <a href="https://www.stellar.org/developers/horizon/reference/errors/stale-history.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk25StaleHistoryErrorResponse")
@interface StaleHistoryErrorResponse : ErrorResponse
@end


SWIFT_CLASS("_TtC10stellarsdk10StellarSDK")
@interface StellarSDK : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10stellarsdk15StreamingHelper")
@interface StreamingHelper : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// See: https://developers.stellar.org/docs/data/horizon/api-reference/submit-async-transaction
SWIFT_CLASS("_TtC10stellarsdk30SubmitTransactionAsyncResponse")
@interface SubmitTransactionAsyncResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a transaction response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/transaction.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk19TransactionResponse")
@interface TransactionResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A successful response to a post transaction request.
/// See <a href="https://www.stellar.org/developers/horizon/reference/endpoints/transactions-create.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk25SubmitTransactionResponse")
@interface SubmitTransactionResponse : TransactionResponse
@end


/// Represents a trade aggregation response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/trade_aggregation.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk24TradeAggregationResponse")
@interface TradeAggregationResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk24TradeAggregationsService")
@interface TradeAggregationsService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a trade effect response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk19TradeEffectResponse")
@interface TradeEffectResponse : EffectResponse
@end


/// Represents the links connected to a trade response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/trade.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk18TradeLinksResponse")
@interface TradeLinksResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents a trade response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/trade.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk13TradeResponse")
@interface TradeResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk13TradesService")
@interface TradesService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk16TradesStreamItem")
@interface TradesStreamItem : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk15TransactionInfo")
@interface TransactionInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Represents the links connected to a transaction response.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/transaction.html">Horizon API</a>
SWIFT_CLASS("_TtC10stellarsdk24TransactionLinksResponse")
@interface TransactionLinksResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk32TransactionPreconditionsResponse")
@interface TransactionPreconditionsResponse : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// Internal error used within some of the responses.
SWIFT_CLASS("_TtC10stellarsdk22TransactionStatusError")
@interface TransactionStatusError : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk24TransactionV0EnvelopeXDR")
@interface TransactionV0EnvelopeXDR : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk24TransactionV1EnvelopeXDR")
@interface TransactionV1EnvelopeXDR : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk19TransactionsService")
@interface TransactionsService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk22TransactionsStreamItem")
@interface TransactionsStreamItem : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk21TransferServerService")
@interface TransferServerService : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10stellarsdk35TrustLineFlagsUpdatedEffectResponse")
@interface TrustLineFlagsUpdatedEffectResponse : EffectResponse
@end


/// Represents an account trustline effect response. Superclass for trustline created, updated, removed, authorized and deauthorized effects.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/assets.html#trustlines">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk23TrustlineEffectResponse")
@interface TrustlineEffectResponse : EffectResponse
@end


/// Represents a trustline authorized effect response. See superclass TrustlineEffect.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/assets.html#trustlines">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk33TrustlineAuthorizedEffectResponse")
@interface TrustlineAuthorizedEffectResponse : TrustlineEffectResponse
@end


/// Represents a trustline authorized to maintain liabilities effect response. See superclass TrustlineEffect.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/assets.html#trustlines">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk53TrustlineAuthorizedToMaintainLiabilitiesEffecResponse")
@interface TrustlineAuthorizedToMaintainLiabilitiesEffecResponse : TrustlineEffectResponse
@end


/// Represents a trustline created effect response. See superclass TrustlineEffect.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/assets.html#trustlines">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk30TrustlineCreatedEffectResponse")
@interface TrustlineCreatedEffectResponse : TrustlineEffectResponse
@end


/// Represents a trustline deauthorized effect response. See superclass TrustlineEffect.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/assets.html#trustlines">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk35TrustlineDeauthorizedEffectResponse")
@interface TrustlineDeauthorizedEffectResponse : TrustlineEffectResponse
@end



/// Represents a trustline removed effect response. See superclass TrustlineEffect.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/assets.html#trustlines">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk30TrustlineRemovedEffectResponse")
@interface TrustlineRemovedEffectResponse : TrustlineEffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk41TrustlineSponsorshipCreatedEffectResponse")
@interface TrustlineSponsorshipCreatedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk41TrustlineSponsorshipRemovedEffectResponse")
@interface TrustlineSponsorshipRemovedEffectResponse : EffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk41TrustlineSponsorshipUpdatedEffectResponse")
@interface TrustlineSponsorshipUpdatedEffectResponse : EffectResponse
@end


/// Represents a trustline updated effect response. See superclass TrustlineEffect.
/// See <a href="https://www.stellar.org/developers/horizon/reference/resources/effect.html">Horizon API</a>
/// See <a href="https://www.stellar.org/developers/guides/concepts/assets.html#trustlines">Stellar guides</a>
SWIFT_CLASS("_TtC10stellarsdk30TrustlineUpdatedEffectResponse")
@interface TrustlineUpdatedEffectResponse : TrustlineEffectResponse
@end


SWIFT_CLASS("_TtC10stellarsdk5TxRep")
@interface TxRep : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// see https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0007.md
SWIFT_CLASS("_TtC10stellarsdk9URIScheme")
@interface URIScheme : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// see  https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0007.md
SWIFT_CLASS("_TtC10stellarsdk18URISchemeValidator")
@interface URISchemeValidator : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
